
project:
  type: website
  output-dir: docs

  render:
    - "*.qmd"
    - "!slides/"
    - "!assignments/"
    - "!_drafts/"

  resources:
    - "slides/output/"

website:
  title: "ST303: Linear Models"
  favicon: ./assets/favicon.png

  site-url: https://c-monaghan.github.io/ST303
  repo-url: https://github.com/C-Monaghan/ST303

  page-navigation: true

  announcement:
    icon: info-circle
    dismissable: false
    content: |
      The first lecture begins on **25th September @12pm**
    type: danger
    position: below-navbar

  navbar:
    pinned: true
    title: Linear Models
    logo: ./assets/figures/favicon.png

    right:
      - text: Overview
        href: content\content_00.qmd
      - text: Week 1
        href: content\content_01.qmd

  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var meta.copyright_year >}} by [{{< var author.name >}}]({{< var author.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}}, [Quarto](https://quarto.org/), and {{< fa heart title='love' aria-hidden='true' >}}<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var meta.project_source >}})

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    toc-location: right
    toc-title: On this page
    smooth-scroll: true
